
[versions]
kotlin-jvm = "2.3.0"

spring-boot2 = "2.7.18"
spring-boot4 = "4.0.1"

spring-cloud2021 = "2021.0.9"
spring-cloud2025 = "2025.1.0"

jupiter-engine = "5.12.1"

[libraries]
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter-engine" }

hutool = { module = "cn.hutool:hutool-all", version = "5.8.42" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin-jvm" }

maven-publish = { id = "maven-publish" }
